### ISSUE TITLE
javax.xml dependency 

### ISSUE THREAD

**Issue by skjolber** [quittle/gradle-android-emulator#85] opened 2020-10-07 11:03 UTC
It seems running with Java 11 does not work because a `ClassNotFoundException` from `javax.xml.*` during resolving dependencies / resources. Seems to work if first running with Java 8 and then 11.

Adding explicit JAXB dependencies would resolve this.

```
> Task :enduser-app:installSdkDependenciesForAndroidEmulatorPlugin FAILED
Non-cacheable because Caching has not been enabled for the task [NOT_CACHEABLE]
Appending implementation to build cache key: org.gradle.api.tasks.Exec_Decorated@166e5a2bef55cafcdeee7602ce34012e
Appending additional implementation to build cache key: org.gradle.api.tasks.Exec_Decorated@166e5a2bef55cafcdeee7602ce34012e
Appending additional implementation to build cache key: com.quittle.androidemulator.AndroidEmulatorPlugin$1@0ab1b5014d7e4dbf85fd172e0a99d907
Appending input value fingerprint for 'args' to build cache key: 81cfd71d82abae790125c43bbb67049d
Appending input value fingerprint for 'command' to build cache key: ef9629ca78b7e53e75f2196d429bf1a8
Appending input value fingerprint for 'environmentMaps' to build cache key: 0bc657b37b1f6c7a9f0495ef507d3697
Appending input value fingerprint for 'executable' to build cache key: 8a7cf548ed0b3fab511f3dd0fc833eca
Appending input value fingerprint for 'ignoreExitValue' to build cache key: c06857e9ea338f3f3a24bb78f8fbdf6f
Appending output property name to build cache key: $1
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by quittle** [comment] 2020-10-07 14:47
I faced this same issue before but this is due to a dependency of the Android plugin, not this one. It does work with JDK 10 as well. I looked into how to mitigate this briefly but didn't find anything.

Are you saying that if this plugin to a direct dependency on the JAXB jars via maven dependencies, it should allow it to work on Java 11?

**Comment by skjolber** [comment] 2020-10-07 19:25
I really don't know where to add JAXB, if it is invoked as an external tool, then perhaps it needs some additional command-line option, if not then perhaps adding JAXB as a dependency will work.

**Comment by quittle** [comment] 2020-10-12 22:26
Hey @skjolber, I've been digging into this a bit and have struggled to reproduce your issue though I know I used to get the exact error you listed. I tried creating a branch that uses JDK 11 and found [Travis builds work](https://travis-ci.com/github/quittle/gradle-android-emulator/builds/189558915). I suspect that the difference is that the `sdkmanager` I'm using comes from the [newer, commandline-tools distribution](https://developer.android.com/studio#cmdline-tools) that Google has been pushing recently. The [older sdk tools](https://developer.android.com/studio/releases/sdk-tools) haven't received an update since 2017 and are marked as deprecated on the official website.

I recommend trying to use the newer commandline tool distribution to provide the `sdkmanager`. I wrote another Gradle plugin [`com.quittle.setup-android-sdk`](https://github.com/quittle/gradle-setup-android-sdk) that will install the modern sdkmanager for you automatically as part of the build and is known to play nicely with this plugin. I've verified it works up through JDK 11.

If you are unable to use the newer commandline tools, please let me know as I'd love to understand your use-case more and may invest in supporting it if there's a breaking change that stops you and others from using this plugin with the newer commandline tools.

**Comment by quittle** [comment] 2020-10-21 23:00
@skjolber did you see my above message? Have you been able to get it working with JDK 11 using the newer command line tools?

**Comment by skjolber** [comment] 2020-10-23 20:32
@quittle sorry, been busy. Will try on Monday.

**Comment by quittle** [comment] 2020-11-06 19:44
Hey @skjolber, have you had a chance to try it out yet?

**Closed** 2020-11-22 23:52 UTC
