### ISSUE TITLE
Android Emulator starts and quits immediately after boot

### ISSUE THREAD

**Issue by anallur** [quittle/gradle-android-emulator#100] opened 2021-01-17 18:36 UTC
We have a custom test runner task, for which we would like to use the emulator plugin as a prerequisite.

However, once we call ./gradlew waitForAndroidEmulator, the Emulator is started, then stopped immediately after boot is completed.

> Task :app:stopAndroidEmulator is automatically run after the above task.

**Comment by quittle** [comment] 2021-01-17 20:44
Hey @anallur, what you have described is expected behavior. In order to keep the emulator running, configure your custom test runner task similar to how the plug-in handles the default one here: https://github.com/quittle/gradle-android-emulator/blob/5e4137117ebeb2fbf273618ff2238a4e41f60aeb/android-emulator-plugin/src/main/java/com/quittle/androidemulator/AndroidEmulatorPlugin.java#L24.  You just need your task to depend on the `waitForAndroidEmulator` and make it finalized by the `stopAndroidEmulator` task. You may also be able flip that and dynamically make your task a dependency of `stopAndroidEmulator`.

I hope this is sufficient to get you unblocked. Let me know if you need more help or have additional questions on how to integrate.

**Comment by anallur** [comment] 2021-01-18 06:42
Thanks for the note. It works well now. However, i get Emulator exited with error 137 at the end of the stopEmulator task. Is it expected ?

**Comment by quittle** [comment] 2021-01-18 13:45
Yeah, that's expected. As far as I know, there's no graceful way to stop the emulator without the UI. It could probably be done cleaner than I have now though since I don't believe I give it time to respond to the initial `sigterm` before sending `sigkill` but it would still be a non-0 exit code.

**Comment by quittle** [comment] 2021-01-29 02:16
@anallur Have I answered your question sufficiently enough to close the issue?

**Comment by anallur** [comment] 2021-01-29 07:43
Yes. The above issues are resolved. But when trying to increase the memory of the emulator using additionalEmulatorArguments -memory=2048 . It fails to launch the emulator.

**Comment by quittle** [comment] 2021-01-29 12:25
Hmm, I recommend setting `logEmulatorOutput true` and rerunning with `--debug`. It will spew a lot more logs but will show the emulator stdout and stderr, including it processing the arguments which should give an indication of the problem.

**Comment by anallur** [comment] 2021-01-29 17:01
Thanks for the information. I was able to find the issue.. 

I was giving the additional arguments as below
`additionalEmulatorArguments  '-no-snapshot', '-wipe-data', '-no-boot-anim', '-memory 3072'`

But it expects it to be 
`additionalEmulatorArguments  '-no-snapshot', '-wipe-data', '-no-boot-anim', '-memory', '3072'`

I suggest you to put this example in the read me. There may be lot other people who may fall in to this trap.

Please go ahead and close this issue

**Comment by quittle** [comment] 2021-01-30 03:47
Thanks for the suggestion. I've updated the README with the instructions I gave you.

**Closed by quittle** 2021-01-30 03:47 UTC
